### ISSUE TITLE
Pull website sections from `numeric_2022`

### ISSUE THREAD

**Issue by douglatornell** [rhwhite/numeric_2022#8]
- [x] getting_started (renamed from course_bootstrap)
- [x] ugradsyllabus (renamed from ugradsyllabus20)
- [x] gradsyllabus (renamed from gradsyllabus20)
- [x] schedule (renamed from schedule20)
- [x] texts
- [x] rubrics
  * done, but `.tex` source files for 2 of the PDFs are MIA; see issues #12 and #13 
- [x] notebook_toc (see #9)

**Comment by douglatornell** [comment]
@SusanEAllen Can you please confirm that all of the sections in the checklist above should be migrated? Feel free to edit the checklist to remove any sections that are cruft.

**Comment by SusanEAllen** [comment]
Re-name course bootstrap as "Getting Started"

Drop Quizzes, we aren't doing them.

Drop solutions as it is a solution to a quiz.
